/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.calculator;

/**
 *
 * @author User
 */
public class moreSet extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public moreSet() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        php = new javax.swing.JButton();
        dollars = new javax.swing.JButton();
        yen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        result = new java.awt.Label();
        times = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        value1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        add4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 158, 159));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 7));
        jPanel1.setForeground(java.awt.SystemColor.text);
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        php.setBackground(new java.awt.Color(254, 95, 85));
        php.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        php.setForeground(new java.awt.Color(238, 245, 219));
        php.setText("Php To $");
        php.setAlignmentY(0.0F);
        php.setBorderPainted(false);
        php.setDefaultCapable(false);
        php.setFocusPainted(false);
        php.setFocusable(false);
        php.setRequestFocusEnabled(false);
        php.setRolloverEnabled(false);
        php.setVerifyInputWhenFocusTarget(false);
        php.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                phpStateChanged(evt);
            }
        });
        php.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpActionPerformed(evt);
            }
        });
        jPanel1.add(php, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 49));

        dollars.setBackground(new java.awt.Color(254, 95, 85));
        dollars.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        dollars.setForeground(new java.awt.Color(238, 245, 219));
        dollars.setText("$ To Php");
        dollars.setAlignmentY(0.0F);
        dollars.setBorderPainted(false);
        dollars.setDefaultCapable(false);
        dollars.setFocusPainted(false);
        dollars.setFocusable(false);
        dollars.setRequestFocusEnabled(false);
        dollars.setRolloverEnabled(false);
        dollars.setVerifyInputWhenFocusTarget(false);
        dollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarsActionPerformed(evt);
            }
        });
        jPanel1.add(dollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, 49));

        yen.setBackground(new java.awt.Color(254, 95, 85));
        yen.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        yen.setForeground(new java.awt.Color(238, 245, 219));
        yen.setText("Php To Yen");
        yen.setAlignmentY(0.0F);
        yen.setBorderPainted(false);
        yen.setDefaultCapable(false);
        yen.setFocusPainted(false);
        yen.setFocusable(false);
        yen.setRequestFocusEnabled(false);
        yen.setRolloverEnabled(false);
        yen.setVerifyInputWhenFocusTarget(false);
        yen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yenActionPerformed(evt);
            }
        });
        jPanel1.add(yen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 170, 49));

        jPanel4.setBackground(new java.awt.Color(252, 214, 193));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        result.setFont(new java.awt.Font("Oceanwide QLt", 0, 21)); // NOI18N
        result.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 360, 70));

        times.setBackground(new java.awt.Color(254, 95, 85));
        times.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        times.setForeground(new java.awt.Color(238, 245, 219));
        times.setText("Yen To Php");
        times.setAlignmentY(0.0F);
        times.setBorderPainted(false);
        times.setDefaultCapable(false);
        times.setFocusPainted(false);
        times.setFocusable(false);
        times.setRequestFocusEnabled(false);
        times.setRolloverEnabled(false);
        times.setVerifyInputWhenFocusTarget(false);
        times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesActionPerformed(evt);
            }
        });
        jPanel1.add(times, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 170, 49));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESULT: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        value1.setBackground(new java.awt.Color(254, 95, 85));
        value1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        value1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        value1.setForeground(new java.awt.Color(238, 245, 219));
        value1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                value1ActionPerformed(evt);
            }
        });
        jPanel1.add(value1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 210, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input Value: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MONEY CONVERTER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        add1.setBackground(new java.awt.Color(252, 214, 193));
        add1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 102, 102));
        add1.setText("BACK");
        add1.setAlignmentY(0.0F);
        add1.setBorderPainted(false);
        add1.setDefaultCapable(false);
        add1.setFocusPainted(false);
        add1.setFocusable(false);
        add1.setRequestFocusEnabled(false);
        add1.setRolloverEnabled(false);
        add1.setVerifyInputWhenFocusTarget(false);
        add1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                add1StateChanged(evt);
            }
        });
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 127, -1));

        add4.setBackground(new java.awt.Color(252, 214, 193));
        add4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        add4.setForeground(new java.awt.Color(0, 102, 102));
        add4.setText("CLEAR");
        add4.setAlignmentY(0.0F);
        add4.setBorderPainted(false);
        add4.setDefaultCapable(false);
        add4.setFocusPainted(false);
        add4.setFocusable(false);
        add4.setRequestFocusEnabled(false);
        add4.setRolloverEnabled(false);
        add4.setVerifyInputWhenFocusTarget(false);
        add4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                add4StateChanged(evt);
            }
        });
        add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add4ActionPerformed(evt);
            }
        });
        jPanel1.add(add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 127, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/calculator/Untitled-1.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpActionPerformed
      double x = Double.parseDouble(value1.getText()); 
       
        double sum = x / 58.69;
        result.setText(String.valueOf("$"+sum));
        String invalid="INPUT A VALUE"; 
         if (x==0){result.setText(String.valueOf(invalid)); 
        result.setText(String.valueOf(sum));     }
    }//GEN-LAST:event_phpActionPerformed

    private void dollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarsActionPerformed
         double x = Double.parseDouble(value1.getText()); 
       
        double sum = x * 58.69;
        result.setText(String.valueOf("Php "+sum));
        String invalid="INPUT A VALUE"; 
         if (x==0){result.setText(String.valueOf(invalid)); 
        result.setText(String.valueOf(sum));     }
    }//GEN-LAST:event_dollarsActionPerformed

    private void yenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yenActionPerformed
 double x = Double.parseDouble(value1.getText()); 
        double sum = x / 0.38;
        String invalid="INPUT A VALUE";   
         result.setText(String.valueOf(sum+" Yen")); 
        if (x==0){result.setText(String.valueOf(invalid)); 
           }
// TODO add your handling code here:
    }//GEN-LAST:event_yenActionPerformed

    private void timesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesActionPerformed
 double x = Double.parseDouble(value1.getText()); 
       
        double sum = x * 0.38;
        result.setText(String.valueOf("Php "+sum)); 
        String invalid="INPUT A VALUE"; 
         if (x==0){result.setText(String.valueOf(invalid)); 
        result.setText(String.valueOf(sum));     }
        // TODO add your handling code here:
    }//GEN-LAST:event_timesActionPerformed

    private void value1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_value1ActionPerformed
     
    }//GEN-LAST:event_value1ActionPerformed

    private void phpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_phpStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_phpStateChanged

    private void add1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_add1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_add1StateChanged

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
 NewJFrame jf2 = new NewJFrame();
      jf2.show();
      dispose();    
    }//GEN-LAST:event_add1ActionPerformed

    private void add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add4ActionPerformed
   double x = Double.parseDouble(value1.getText()); 
       
        String sum5 = "";
        
        result.setText(String.valueOf(sum5));      
               // TODO add your handling code here:
    }//GEN-LAST:event_add4ActionPerformed

    private void add4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_add4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_add4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
  try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(moreSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(moreSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(moreSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(moreSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new moreSet().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton dollars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton php;
    private java.awt.Label result;
    private javax.swing.JButton times;
    private java.awt.TextField value1;
    private javax.swing.JButton yen;
    // End of variables declaration//GEN-END:variables
}
