/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame.calculator;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        div = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        result = new java.awt.Label();
        times = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        value1 = new java.awt.TextField();
        value2 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        add4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 158, 159));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 7));
        jPanel1.setForeground(java.awt.SystemColor.text);
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(254, 95, 85));
        add.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        add.setForeground(new java.awt.Color(238, 245, 219));
        add.setText("SUM");
        add.setAlignmentY(0.0F);
        add.setBorderPainted(false);
        add.setDefaultCapable(false);
        add.setFocusPainted(false);
        add.setFocusable(false);
        add.setRequestFocusEnabled(false);
        add.setRolloverEnabled(false);
        add.setVerifyInputWhenFocusTarget(false);
        add.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                addStateChanged(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 127, 49));

        minus.setBackground(new java.awt.Color(254, 95, 85));
        minus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        minus.setForeground(new java.awt.Color(238, 245, 219));
        minus.setText("DIFFERENCE");
        minus.setAlignmentY(0.0F);
        minus.setBorderPainted(false);
        minus.setDefaultCapable(false);
        minus.setFocusPainted(false);
        minus.setFocusable(false);
        minus.setRequestFocusEnabled(false);
        minus.setRolloverEnabled(false);
        minus.setVerifyInputWhenFocusTarget(false);
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel1.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 127, 49));

        div.setBackground(new java.awt.Color(254, 95, 85));
        div.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        div.setForeground(new java.awt.Color(238, 245, 219));
        div.setText("QUOTIENT");
        div.setAlignmentY(0.0F);
        div.setBorderPainted(false);
        div.setDefaultCapable(false);
        div.setFocusPainted(false);
        div.setFocusable(false);
        div.setRequestFocusEnabled(false);
        div.setRolloverEnabled(false);
        div.setVerifyInputWhenFocusTarget(false);
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 127, 49));

        jPanel4.setBackground(new java.awt.Color(252, 214, 193));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        result.setFont(new java.awt.Font("Oceanwide QLt", 0, 24)); // NOI18N
        result.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 360, 70));

        times.setBackground(new java.awt.Color(254, 95, 85));
        times.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        times.setForeground(new java.awt.Color(238, 245, 219));
        times.setText("PRODUCT");
        times.setAlignmentY(0.0F);
        times.setBorderPainted(false);
        times.setDefaultCapable(false);
        times.setFocusPainted(false);
        times.setFocusable(false);
        times.setRequestFocusEnabled(false);
        times.setRolloverEnabled(false);
        times.setVerifyInputWhenFocusTarget(false);
        times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesActionPerformed(evt);
            }
        });
        jPanel1.add(times, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 127, 49));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESULT: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        value1.setBackground(new java.awt.Color(254, 95, 85));
        value1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        value1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        value1.setForeground(new java.awt.Color(238, 245, 219));
        value1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                value1ActionPerformed(evt);
            }
        });
        jPanel1.add(value1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 184, 35));

        value2.setBackground(new java.awt.Color(254, 95, 85));
        value2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        value2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        value2.setForeground(new java.awt.Color(238, 245, 219));
        jPanel1.add(value2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 184, 35));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" FIRST VALUE: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 35));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" SECOND VALUE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 136, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CALCULATOR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 13, -1, -1));

        add1.setBackground(new java.awt.Color(252, 214, 193));
        add1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        add1.setForeground(new java.awt.Color(0, 102, 102));
        add1.setText("MORE");
        add1.setAlignmentY(0.0F);
        add1.setBorderPainted(false);
        add1.setDefaultCapable(false);
        add1.setFocusPainted(false);
        add1.setFocusable(false);
        add1.setRequestFocusEnabled(false);
        add1.setRolloverEnabled(false);
        add1.setVerifyInputWhenFocusTarget(false);
        add1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                add1StateChanged(evt);
            }
        });
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 127, -1));

        add4.setBackground(new java.awt.Color(252, 214, 193));
        add4.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        add4.setForeground(new java.awt.Color(0, 102, 102));
        add4.setText("CLEAR");
        add4.setAlignmentY(0.0F);
        add4.setBorderPainted(false);
        add4.setDefaultCapable(false);
        add4.setFocusPainted(false);
        add4.setFocusable(false);
        add4.setRequestFocusEnabled(false);
        add4.setRolloverEnabled(false);
        add4.setVerifyInputWhenFocusTarget(false);
        add4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                add4StateChanged(evt);
            }
        });
        add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add4ActionPerformed(evt);
            }
        });
        jPanel1.add(add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 127, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/calculator/Untitled-1.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      double x = Double.parseDouble(value1.getText()); 
        double y = Double.parseDouble(value2.getText()); 
        double sum = x + y;
        result.setText(String.valueOf("SUM: "+sum));
        
    }//GEN-LAST:event_addActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
         double x = Double.parseDouble(value1.getText()); 
        double y = Double.parseDouble(value2.getText()); 
        double min = x - y;
        result.setText(String.valueOf("DIFFERENCE: "+min));
    }//GEN-LAST:event_minusActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
 double x = Double.parseDouble(value1.getText()); 
        double y = Double.parseDouble(value2.getText()); 
        double divide = x / y;
        String invalid="MATH ERROR";
        result.setText(String.valueOf("QUOTIENT: "+divide));      
        if (x==0){result.setText(String.valueOf(invalid));  }
 if (y==0){result.setText(String.valueOf(invalid));  }// TODO add your handling code here:
    }//GEN-LAST:event_divActionPerformed

    private void timesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesActionPerformed
 double x = Double.parseDouble(value1.getText()); 
        double y = Double.parseDouble(value2.getText()); 
        double prod = x * y;
        result.setText(String.valueOf("PRODUCT: "+prod));        // TODO add your handling code here:
    }//GEN-LAST:event_timesActionPerformed

    private void value1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_value1ActionPerformed
     
    }//GEN-LAST:event_value1ActionPerformed

    private void addStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_addStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addStateChanged

    private void add1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_add1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_add1StateChanged

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
      moreSet jf2 = new moreSet();
      jf2.show();
      dispose(); 
       
    }//GEN-LAST:event_add1ActionPerformed

    private void add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add4ActionPerformed
     String blnk= "";
        result.setText(String.valueOf(blnk)); 
    }//GEN-LAST:event_add4ActionPerformed

    private void add4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_add4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_add4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
  try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new NewJFrame().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JButton add4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton div;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton minus;
    private java.awt.Label result;
    private javax.swing.JButton times;
    private java.awt.TextField value1;
    private java.awt.TextField value2;
    // End of variables declaration//GEN-END:variables
}
